### ISSUE TITLE
Portability Boost & Sudo

### ISSUE THREAD

**Issue by ghost** [Misko-2083/Installer#1]
Hi, thought I'd check out some of your stuff, to see if I could return the favor for your recent issue thread. This one is regarding this file and line:

https://github.com/Misko-2083/Installer/blob/master/custom-installer#L17

How's this? Saves using awk, or cut and grep. Also a bit more readable than a long, one-liner.

```bash
chklist=()
for k in "${!apps[@]}"; do
        while read -a X; do
                # Grab and set a var for the build.
                if [ "${X[0]}" == "Installed:" ]; then
                        printf -v Y "%s\n" "${X[1]}"
                        break # To avoid extra processing.
                fi
        done <<< "$(apt-cache policy "${apps[$k]%%_*}")"
        chklist+=("FALSE" "$k" "${apps[$k]#*_}" "$y")
done
```

NOTE: I haven't tested it with your code, but the while loop is fine for me on its own. I'm using bash 4.3.48(1)-release.

I'd also like to suggest you use gksudo instead of sudo, since it's a GUI-focused installer. This worked really nicely when I tried it with your installer in a Mint 18.2 virtual machine. I love your use of Zenity, by the way. Didn't realise how versatile it is!

**Comment by Misko-2083** [comment]
Thanks for dropping by.
This script is simplified version of the script for [linux lite](https://github.com/linuxlite/litesoftware/blob/master/usr/bin/lite-software) for some packages I used that were not on the list in lite-software. I haven't updated it in a while.

Nested loop and reading elements into array is indeed a good idea. I like your pure bash approach.
I've had some wrapper script that used to launch this script with gksudo. You're right, it's more convenient to keep it in the same script.
There is also inconsistency in adding rows to zenity --list dialog. Aqualung is in the last row.
I'm thinking of adding the check for exclusive lock in case the package manager has aplied it.
```bash
while  fuser /var/lib/dpkg/lock 2>&1 >/dev/null  ; do
       echo "waiting for package manager to close" 
       sleep 1
done
```
I will update the script soon.

Haven't used zenity much lately. I mostly used yad (Yet Another Dialog). It's more advanced.

**Comment by ghost** [comment]
Not a problem, and thank you. Happy to help.

I've never heard of yad, but checking it out now and it looks awesome! Might save me some time making tkinter GUIs in Python. Even on my minimalistic Ubuntu-based setup I didn't need anything but the yad package itself; of this I highly approve.

**Comment by Misko-2083** [comment]
That should be it. 0181056 f3ebbcc
It should open a little faster and the rows are populated correctly.
I've added a hidden column to store the keys. Also zenity prints only this column on output.

For yad, some good examples are here:
[https://sourceforge.net/p/yad-dialog/wiki/browse_pages/](https://sourceforge.net/p/yad-dialog/wiki/browse_pages/ )

smokey01 also has some basic examples [http://smokey01.com/yad/](http://smokey01.com/yad/)

I have a youtube-dl wrapper that downloads videos from youtube [yt-get](https://github.com/Misko-2083/yt-get/blob/master/yt-get ) that uses yad.

Thanks for helping.
